### PR TITLE
Add pagination to the cards endpoint

### PR DESCRIPTION
**Pull request by filipefigcorreia**
Adds documentation for the newly introduced cards pagination.

### CODE REVIEW

**Comment by fixe** [comment]
@filipefigcorreia please improve the commit title and add a description.

**Comment by tfmf** [comment]
@filipefigcorreia can you also indicate the number of cards returned per request?

**Comment by filipefigcorreia** [comment]
@tfmf the number of items will be the one specified in the request through the `Range` header. Is this what you meant?

**Comment by tfmf** [comment]
@filipefigcorreia yes, that works.

**Pull request merged**
